version: "1.0"

deployment:
  project: saturnia-demo
  environment: production
  defaultNetwork: saturnia-net
  autoExpose: true
  entryService: web
  domains:
    - domain: app.saturnia.io
      service: web
      proxy: true
      ssl: true
      forceHttps: true
    - domain: api.saturnia.io
      service: api
      proxy: true
      ssl: true
      forceHttps: false

services:
  web:
    build:
      context: ./Saturnia.Web
      dockerfile: Dockerfile
    ports:
      - 80:80
    env:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - api
    expose: true

  api:
    build:
      context: ./Saturnia.API
      dockerfile: Dockerfile
    ports:
      - 5000:80
    env:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=postgresql://admin:admin@db:5432/saturnia
    volumes:
      - logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env:
      - POSTGRES_DB=saturnia
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    expose: false

volumes:
  logs:
  db-data:

networks:
  saturnia-net:
    driver: bridge
